// Import script for ik_test candidate KG CSVs generated by:
// Eval/build_ik_test_candidate_kg_for_neo4j.py
//
// Copy CSV files into Neo4j import directory first.
// Then run this script in Neo4j Browser or cypher-shell.

CREATE CONSTRAINT case_id_unique IF NOT EXISTS
FOR (c:Case) REQUIRE c.case_id IS UNIQUE;

CREATE CONSTRAINT label_name_unique IF NOT EXISTS
FOR (l:Label) REQUIRE l.name IS UNIQUE;

LOAD CSV WITH HEADERS FROM 'file:///ik_test_candidate_kg_case_nodes.csv' AS row
MERGE (c:Case {case_id: row.case_id})
SET c.label_count = toInteger(row.label_count),
    c.labels = split(coalesce(row.labels, ''), '|');

LOAD CSV WITH HEADERS FROM 'file:///ik_test_candidate_kg_label_nodes.csv' AS row
MERGE (l:Label {name: row.label_name});

LOAD CSV WITH HEADERS FROM 'file:///ik_test_candidate_kg_case_label_edges.csv' AS row
MATCH (c:Case {case_id: row.case_id})
MATCH (l:Label {name: row.label_name})
MERGE (c)-[:HAS_LABEL]->(l);

LOAD CSV WITH HEADERS FROM 'file:///ik_test_candidate_kg_case_case_edges.csv' AS row
MATCH (a:Case {case_id: row.source_case_id})
MATCH (b:Case {case_id: row.target_case_id})
MERGE (a)-[r:SIMILAR_LABELS]->(b)
SET r.shared_count = toInteger(row.shared_count),
    r.shared_labels = split(coalesce(row.shared_labels, ''), '|');

// Quick visualization query:
MATCH (c1:Case)-[r:SIMILAR_LABELS]->(c2:Case)
WHERE r.shared_count >= 2
RETURN c1, r, c2
ORDER BY r.shared_count DESC
LIMIT 200;
